sudo: false

language: go

# Whenever the Go version is updated here, .circleci/config.yml and .promu.yml
# should also be updated.
go:
- 1.13.x

go_import_path: github.com/woraser/blackbox_exporter

script:
- make
- git diff --exit-code
